POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRkYW1vbiIsImlkIjoiNjEwZDUzMGRjODllZTUxMjhlZWRhZGUwIiwiaWF0IjoxNjI4MjYzMjAxLCJleHAiOjE2MjgyNjY4MDF9.I-iMpf82i0TYyvGSaJimXkGm6PAL5899QgHFWoyu7sY

{
  "title": "Faraway galaxy",
  "author": "Luke Skywalker",
  "url": "https://example.com"
}
